print("=" * 40)

print("Student Information System")
print("=" * 40)

student_name = input("Enter Student Name:")
student_age = int(input("Enter Student Age:"))
student_class = int(input("Enter Student Class:"))
student_email = input("Enter Student Email:")
student_dream_project = input("Enter Student Dream Project:")
student_percentage = float(input("Enter Student Percentage:"))
print("=" * 40)
print("--------- Student Details -----------")
print("=" * 40)
print(f"Student Name            : {student_name}")
print(f"Student Age             : {student_age}")
print(f"Student Class           : {student_class}")
print(f"Student Email           : {student_email}")
print(f"Student Dream Project   : {student_dream_project}")
print(f"Student Percentage      : {student_percentage}")
print("=" * 40)