print("=" * 40)
name=input("Enter Your Name:")
age=int(input("Enter Your Age:"))
city=input("Enter Your City:")
feb_lang=input("Enter Your Favorite Programming Language:")
print("=" * 40)
print("---------Output---------")
print("Your Name is:", name)
print("Your Age is: ", age)
print("Your City is:", city)
print("Your Favorite Programming Language is:", feb_lang)
print("=" * 40)
