print("=" * 40)
print("Student Information System")
print("=" * 40)

name=input("Enter Your Name:")
age=int(input("Enter Your Age:"))
city=input("Enter Your City:")
course=input("Enter Course:")
print()
print("Student Details")
print("---------------------")
print("Name: ", name)
print("Age: ", age)
print("City: ", city)
print("Course: ", course)
print("=" * 40)