print("=" * 40)
print("Welcome to my AI Journey")
print("=" * 40)
print("Name: Anendra Patel")
print("Goal: Become A Generative AI Engineer")
print("=" * 40)
print("Future Projects")
print("1. AI Coding Assistant")
print("2. AI Crypte Research Platform")
print("3. AI Agents")
print("4. AI Saas")
print("=" * 40)